name: place_picker
description: Place picker fully written in dart for Flutter. Comes with
  autocomplete suggestions and nearby locations list. Localization too.
version: 0.9.18-nullsafety
homepage: https://github.com/blackmann/locationpicker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.1.1
  google_maps_flutter: ^2.0.1
  http: ^0.13.1
  location: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: null
